COMPOSITE: '1'
CREATION_DATE: September 20, 2017 14:30 UTC
DATA_CMNT: RCMsn173_edited.txt
EDIT_CMNT01: ''
EPIC_FILE_GENERATOR: nc_epic2udunits_time.py V0.4.0
EXPERIMENT: ''
History: '

  September 07, 2017 20:53 UTC Magnetic Declination Correction 10.97828924 applied
  (+E)

  September 08, 2017 17:50 UTC - Oxygen Concentration and Saturation corrected for
  salinity using 16BS2C 12m sbe-16 September 20, 2017 14:30 UTC EPIC two time-word
  key converted to udunits

  '
INST_TYPE: rcmsg
MOORING: 16bs2c
PROG_CMNT01: ''
PROJECT: ''
WATER_DEPTH: '71'
WATER_MASS: ''
featureType: timeSeries
